version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8088:8088
    depends_on:
      - maria_db
    links:
      - maria_db:app_db
  maria_db:
    image: "mariadb:10.4"
    restart: always
    ports:
      - 3309:3309
    environment:
      MYSQL_DATABASE: event_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root