version: "2.2"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 0.0.0.0:8080:8088
    depends_on:
      - maria_db
    links:
      - maria_db:app_db
  maria_db:
    image: "mariadb:10.4"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: event_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root